### ISSUE TITLE
Cannot check readiness of a request with no selected adapters

### ISSUE THREAD

**Issue by shahidghafoor00** [tapdaq/tapdaq-ios-samples#1]
I have added interstitial ad and when I use admob id of interstitial ad, I get this error. 
Test ID is working perfectly fine.

**Comment by rdominic** [comment]
Apologies we couldn't help here. Unfortunately Tapdaq is being deprecated and its services turned off.
All public SDK repo's will be archived shortly and changed to private later this year.

For an alternative mediation platform we recommend IronSource.

Closing this ticket.
